-- CreateTable
CREATE TABLE "employees" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "nombres" TEXT NOT NULL,
    "apellidoPaterno" TEXT NOT NULL,
    "apellidoMaterno" TEXT NOT NULL,
    "nombreCompleto" TEXT NOT NULL,
    "tipoDocumento" TEXT NOT NULL,
    "numeroDocumento" TEXT NOT NULL,
    "fechaNacimiento" DATETIME NOT NULL,
    "lugarNacimiento" TEXT,
    "sexo" TEXT,
    "estadoCivil" TEXT,
    "nacionalidad" TEXT,
    "direccion" TEXT,
    "departamento" TEXT,
    "provincia" TEXT,
    "distrito" TEXT,
    "telefono" TEXT,
    "email" TEXT,
    "emailCorporativo" TEXT,
    "nivelEducativo" TEXT,
    "profesion" TEXT,
    "licenciaConducir" TEXT,
    "hijos" INTEGER NOT NULL DEFAULT 0,
    "banco" TEXT,
    "tipoCuenta" TEXT,
    "numeroCuenta" TEXT,
    "numeroCCI" TEXT,
    "nombreConyuge" TEXT,
    "dniConyuge" TEXT,
    "nombrePadre" TEXT,
    "nombreMadre" TEXT,
    "foto" TEXT,
    "fotoDNI" TEXT,
    "fotoRUC" TEXT,
    "estado" TEXT NOT NULL DEFAULT 'ACTIVO',
    "fechaIngreso" DATETIME NOT NULL,
    "fechaCese" DATETIME,
    "motivoCese" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "contracts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "tipoContrato" TEXT NOT NULL,
    "regimenLaboral" TEXT NOT NULL,
    "modalidadContrato" TEXT,
    "fechaInicio" DATETIME NOT NULL,
    "fechaFin" DATETIME,
    "duracionMeses" INTEGER,
    "cargo" TEXT NOT NULL,
    "puesto" TEXT,
    "categoriaOcupacional" TEXT,
    "nivel" TEXT,
    "centroCostos" TEXT,
    "departamentoTrabajo" TEXT,
    "areaTrabajo" TEXT,
    "turno" TEXT,
    "horarioTrabajo" TEXT,
    "diasTrabajo" INTEGER NOT NULL DEFAULT 6,
    "horasSemanales" INTEGER NOT NULL DEFAULT 48,
    "salarioBase" REAL NOT NULL,
    "tipoMoneda" TEXT NOT NULL DEFAULT 'PEN',
    "formaPago" TEXT NOT NULL DEFAULT 'MENSUAL',
    "medioPago" TEXT NOT NULL DEFAULT 'DEPOSITO',
    "asignacionFamiliar" REAL NOT NULL DEFAULT 93.00,
    "bonificacionProductividad" REAL,
    "bonificacionPuesto" REAL,
    "movilidad" REAL,
    "refrigerio" REAL,
    "seguroSalud" TEXT,
    "nombreEPS" TEXT,
    "afp" TEXT,
    "nombreAFP" TEXT,
    "cuspp" TEXT,
    "tipoSeguro" TEXT,
    "tieneCTS" BOOLEAN NOT NULL DEFAULT true,
    "tieneVacaciones" BOOLEAN NOT NULL DEFAULT true,
    "tieneGratificaciones" BOOLEAN NOT NULL DEFAULT true,
    "tieneUtilidades" BOOLEAN NOT NULL DEFAULT true,
    "estado" TEXT NOT NULL DEFAULT 'VIGENTE',
    "motivoSuspension" TEXT,
    "archivoContrato" TEXT,
    "archivoAddendum" TEXT,
    "createdById" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "contracts_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "overtime_hours" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "contratoId" TEXT NOT NULL,
    "fecha" DATETIME NOT NULL,
    "diaSemana" INTEGER NOT NULL,
    "horaInicio" TEXT NOT NULL,
    "horaFin" TEXT NOT NULL,
    "totalHoras" REAL NOT NULL,
    "tipoHora" TEXT NOT NULL,
    "motivo" TEXT,
    "supervisorId" TEXT,
    "estado" TEXT NOT NULL DEFAULT 'SOLICITADO',
    "montoCalculado" REAL,
    "fechaAprobacion" DATETIME,
    "aprobadoPor" TEXT,
    "comentarios" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "overtime_hours_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "overtime_hours_contratoId_fkey" FOREIGN KEY ("contratoId") REFERENCES "contracts" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "employee_loans" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "contratoId" TEXT NOT NULL,
    "tipoPrestamo" TEXT NOT NULL,
    "montoSolicitado" REAL NOT NULL,
    "montoAprobado" REAL NOT NULL,
    "tasaInteresMensual" REAL NOT NULL,
    "cantidadCuotas" INTEGER NOT NULL,
    "fechaOtorgamiento" DATETIME NOT NULL,
    "fechaPrimerDescuento" DATETIME NOT NULL,
    "cuotaMensual" REAL NOT NULL,
    "saldoPendiente" REAL NOT NULL,
    "estado" TEXT NOT NULL DEFAULT 'SOLICITADO',
    "garantia" TEXT,
    "cuotasPagadas" INTEGER NOT NULL DEFAULT 0,
    "proximaCuota" INTEGER NOT NULL DEFAULT 1,
    "fechaUltimoPago" DATETIME,
    "aprobadoPor" TEXT,
    "fechaAprobacion" DATETIME,
    "observaciones" TEXT,
    "archivoSolicitud" TEXT,
    "archivoContrato" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "employee_loans_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "employee_loans_contratoId_fkey" FOREIGN KEY ("contratoId") REFERENCES "contracts" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "loan_installments" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "prestamoId" TEXT NOT NULL,
    "numeroCuota" INTEGER NOT NULL,
    "fechaVencimiento" DATETIME NOT NULL,
    "montoCuota" REAL NOT NULL,
    "interes" REAL NOT NULL,
    "capital" REAL NOT NULL,
    "saldoCapital" REAL NOT NULL,
    "estado" TEXT NOT NULL DEFAULT 'PENDIENTE',
    "fechaPago" DATETIME,
    "montoPagado" REAL,
    "mora" REAL NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "loan_installments_prestamoId_fkey" FOREIGN KEY ("prestamoId") REFERENCES "employee_loans" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "deductions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "contratoId" TEXT NOT NULL,
    "periodo" TEXT NOT NULL,
    "tipoDescuento" TEXT NOT NULL,
    "concepto" TEXT NOT NULL,
    "monto" REAL NOT NULL,
    "porcentaje" REAL,
    "baseCalculo" REAL,
    "descripcion" TEXT,
    "referencia" TEXT,
    "estado" TEXT NOT NULL DEFAULT 'PENDIENTE',
    "creadoPor" TEXT,
    "fechaCreacion" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "autorizadoPor" TEXT,
    "fechaAutorizacion" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "deductions_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "deductions_contratoId_fkey" FOREIGN KEY ("contratoId") REFERENCES "contracts" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "payroll" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "contratoId" TEXT NOT NULL,
    "periodo" TEXT NOT NULL,
    "salarioBase" REAL NOT NULL,
    "horasExtras25" REAL NOT NULL DEFAULT 0,
    "horasExtras35" REAL NOT NULL DEFAULT 0,
    "horasExtras100" REAL NOT NULL DEFAULT 0,
    "bonificacionProductividad" REAL NOT NULL DEFAULT 0,
    "bonificacionPuesto" REAL NOT NULL DEFAULT 0,
    "asignacionFamiliar" REAL NOT NULL DEFAULT 93.00,
    "movilidad" REAL NOT NULL DEFAULT 0,
    "refrigerio" REAL NOT NULL DEFAULT 0,
    "vacacionesTruncas" REAL NOT NULL DEFAULT 0,
    "CTS" REAL NOT NULL DEFAULT 0,
    "gratificacion" REAL NOT NULL DEFAULT 0,
    "utilidades" REAL NOT NULL DEFAULT 0,
    "totalAFP_ONP" REAL NOT NULL DEFAULT 0,
    "totalEssalud" REAL NOT NULL DEFAULT 0,
    "totalSCTR" REAL NOT NULL DEFAULT 0,
    "quintaCategoria" REAL NOT NULL DEFAULT 0,
    "prestamos" REAL NOT NULL DEFAULT 0,
    "adelantos" REAL NOT NULL DEFAULT 0,
    "faltasInjustificadas" REAL NOT NULL DEFAULT 0,
    "tardanzas" REAL NOT NULL DEFAULT 0,
    "otrosDescuentos" REAL NOT NULL DEFAULT 0,
    "aporteObligatorio" REAL NOT NULL DEFAULT 0,
    "comisionFlujo" REAL NOT NULL DEFAULT 0,
    "primaSeguro" REAL NOT NULL DEFAULT 0,
    "totalIngresos" REAL NOT NULL,
    "totalDescuentos" REAL NOT NULL,
    "netoPagar" REAL NOT NULL,
    "estado" TEXT NOT NULL DEFAULT 'BORRADOR',
    "fechaProceso" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "procesadoPor" TEXT,
    "aprobadoPor" TEXT,
    "fechaPago" DATETIME,
    "bancoPago" TEXT,
    "numeroReferencia" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "payroll_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "payroll_contratoId_fkey" FOREIGN KEY ("contratoId") REFERENCES "contracts" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "leaves_permissions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "contratoId" TEXT NOT NULL,
    "tipoPermiso" TEXT NOT NULL,
    "fechaInicio" DATETIME NOT NULL,
    "fechaFin" DATETIME NOT NULL,
    "cantidadDias" INTEGER NOT NULL,
    "motivo" TEXT,
    "soporteMedico" TEXT,
    "estado" TEXT NOT NULL DEFAULT 'SOLICITADO',
    "aprobadoPor" TEXT,
    "fechaAprobacion" DATETIME,
    "comentarios" TEXT,
    "diasDisponibles" INTEGER,
    "diasUtilizados" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "leaves_permissions_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "leaves_permissions_contratoId_fkey" FOREIGN KEY ("contratoId") REFERENCES "contracts" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "attendance_control" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "contratoId" TEXT NOT NULL,
    "fecha" DATETIME NOT NULL,
    "horaEntrada" TEXT,
    "horaSalida" TEXT,
    "tipoControl" TEXT NOT NULL,
    "minutosTardanza" INTEGER NOT NULL DEFAULT 0,
    "minutosFalta" INTEGER NOT NULL DEFAULT 0,
    "motivo" TEXT,
    "justificado" BOOLEAN NOT NULL DEFAULT false,
    "documentoJustificacion" TEXT,
    "estado" TEXT NOT NULL DEFAULT 'PENDIENTE',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "attendance_control_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "attendance_control_contratoId_fkey" FOREIGN KEY ("contratoId") REFERENCES "contracts" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "withholdings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "empleadoId" TEXT NOT NULL,
    "contratoId" TEXT NOT NULL,
    "periodo" TEXT NOT NULL,
    "tipoDetraccion" TEXT NOT NULL,
    "baseImponible" REAL NOT NULL,
    "porcentaje" REAL NOT NULL,
    "montoDetraccion" REAL NOT NULL,
    "estado" TEXT NOT NULL DEFAULT 'PENDIENTE',
    "fechaDeclaracion" DATETIME,
    "fechaPago" DATETIME,
    "numeroConstancia" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "withholdings_empleadoId_fkey" FOREIGN KEY ("empleadoId") REFERENCES "employees" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "withholdings_contratoId_fkey" FOREIGN KEY ("contratoId") REFERENCES "contracts" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "employees_numeroDocumento_key" ON "employees"("numeroDocumento");

